### ISSUE TITLE
Option to build web-version P2P (with `webxdc-x-web`)

### ISSUE THREAD

**Issue by WofWca** [webxdc/vite-plugins#1]
See [this forum post](https://support.delta.chat/t/make-all-webxdc-apps-web-ready-again-effortlessly-with-webrtc-webxdc-x-web/2683/2?u=wofwca). [The `webxdc-x-web` library](https://codeberg.org/WofWca/webxdc-x-web) is still not production ready, but I just want to throw it out there.

**Comment by adbenitez** [comment]
I don't think this is necessary as providing the fake webxdc.js is really easy as you can see in the [Public Bots index](https://deltachat-bot.github.io/public-bots)
