### ISSUE TITLE
use upstream emulator from hello

### ISSUE THREAD

**Issue by Simon-Laux** [webxdc/vite-plugins#2]
would be good if there were synced somehow, like it being also an npm package.

**Comment by adbenitez** [comment]
it would be nice but for that we first need the emulator to be in npm, I think it makes sense if the basic emulator is part of the webxdc-dev package, that anyways also need it

**Comment by Simon-Laux** [comment]
> I think it makes sense if the basic emulator is part of the webxdc-dev package, that anyways also need it

webxdc-dev has it's own emulator
