### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by Simon-Laux** [webxdc/vite-plugins#4]
to prevent pnpm caching bugs like #3 

to add insult to injury the readme claims it is already on npm:

https://github.com/webxdc/webxdc-vite-plugins/blob/cff793a3a3c637c891a5bcd1e9bf50f3bab86992/README.md?plain=1#L10-L16

after publishing update https://github.com/webxdc/webxdc-vite so that it references the npm package (currently the lock file makes it use an old version with #3 bug)

**Comment by adbenitez** [comment]
> to prevent pnpm caching bugs like #3

user can pin/update version like this:

```
"webxdc-vite-plugins": "github:webxdc/webxdc-vite-plugins#0.3.0"
```


would be nice to put it in npm, could you help with that @Simon-Laux ? I have zero experience with that, have never published, also the package needs to be converted to type module before vite v6 is released, as CJS support is deprecated

or if at least you could point me to some docs/tutorial I could follow, I struggled a lot even to make the package work as github dependency,  it is using old `require()` etc

**Comment by Simon-Laux** [comment]
> or if at least you could point me to some docs/tutorial I could follow

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

basically use import instead of require. dynamic `import()` is async so prefer the static import on top of files, look into dc-desktop code or on the mdn website I linked above to see how it looks. Also in `package.json` you need to set `"type":"module"` otherwise nodejs thinks it is a CJS module, unless you rename all files to `.mjs`.

For publishing it would be best if you make an organisation on npm and then invite me and others to it.
Then prefix package name with that organisation, so for example `@webxdc/vite-plugins`.
When you get a "you can not publish private packages" error while running `npm publish`, then set some cli argument, I think it was `--access=public`.

**Comment by adbenitez** [comment]
thanks a lot for the help, the package is now available here:
https://www.npmjs.com/package/@webxdc/vite-plugins
